# Site settings
title: Noon Universe
email: MarkBruns@MarkBruns.com
description: Noon Universe Space Exploration
twitter_username: MarkBruns
github_username:  NoonU-Space

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
