# Site settings
title: WIGOUT.land
email: MarkBruns@MarkBruns.com
description: Western Iowa Greenspace Organization United for TURKEYS (WIGOUT) ... Wigout.land
twitter_username: MarkBruns
github_username:  WIGOUTland

# Build settings
markdown: kramdown

theme: jekyll-theme-time-machine
